### ISSUE TITLE
Details about training

### ISSUE THREAD

**Issue by fangchuan** [sony/genwarp#7]
Dear authors, thanks for your sharing this wonderful work!

I have some questions about training details, which are not mentioned in your paper.
1. how many iterations do you train the two branch networks?
2. How do you add the coordinate map for the input view and target view? element-wise addition or channel-wise concatnation? It looks weird that Plucker ray embedding works poor in your Ablation Table.2

Many thanks for your reply! I am looking forward it @kaz-sony

**Comment by kaz-sony** [comment]
Hi @fangchuan , Thank you for your interest.

> 1. how many iterations do you train the two branch networks?

For each training checkpoints, we used the settings below:

- multi1
  - dataset: RealEstate10K, ACID, ScanNet
  - trained for 102000 steps with batch size 48
- multi2
  - dataset: RealEstate10K, ACID, ScanNet, MegaScene v1.0
  - trained for 344000 steps with batch size 192

> 2. How do you add the coordinate map for the input view and target view? element-wise addition or channel-wise concatnation? It looks weird that Plucker ray embedding works poor in your Ablation Table.2

It is 'element-wise addition' as you can confirm it with the codes [here](https://github.com/sony/genwarp/blob/main/genwarp/models/unet_2d_condition.py#L1151).

One of the reason why the performance of the Plücker embedding was lower than that of our warped coordinates embedding in our experiment is because ours incorporates the estimated depth information by warping the coordinates while Plücker only carries the information of the relative camera pose. Another reason is that Plücker embedding is known to suffer from scale ambiguity when in the situations like single-shot NVS setting, which is our main target. This is well described in [pixelSplat](https://arxiv.org/abs/2312.12337) paper (see fig.2). The problem might not be such a big issue when the model is multi-view generation with any given trajectory unlike us, because in such cases the model can find a reasonable scaling by generating images of one object from multiple views (Imagine generating multi-view images of a cat from a camera with a circular motion revolving about the cat). This is the case for the existing methods like SPAD and CAT3D as you may have already seen.

Let us know if you have further questions.

**Comment by fangchuan** [comment]
> Hi @fangchuan , Thank you for your interest.
> 
> > 1. how many iterations do you train the two branch networks?
> 
> For each training checkpoints, we used the settings below:
> 
> * multi1
>   
>   * dataset: RealEstate10K, ACID, ScanNet
>   * trained for 102000 steps with batch size 48
> * multi2
>   
>   * dataset: RealEstate10K, ACID, ScanNet, MegaScene v1.0
>   * trained for 344000 steps with batch size 192
> 
> > 2. How do you add the coordinate map for the input view and target view? element-wise addition or channel-wise concatnation? It looks weird that Plucker ray embedding works poor in your Ablation Table.2
> 
> It is 'element-wise addition' as you can confirm it with the codes [here](https://github.com/sony/genwarp/blob/main/genwarp/models/unet_2d_condition.py#L1151).
> 
> One of the reason why the performance of the Plücker embedding was lower than that of our warped coordinates embedding in our experiment is because ours incorporates the estimated depth information by warping the coordinates while Plücker only carries the information of the relative camera pose. Another reason is that Plücker embedding is known to suffer from scale ambiguity when in the situations like single-shot NVS setting, which is our main target. This is well described in [pixelSplat](https://arxiv.org/abs/2312.12337) paper (see fig.2). The problem might not be such a big issue when the model is multi-view generation with any given trajectory unlike us, because in such cases the model can find a reasonable scaling by generating images of one object from multiple views (Imagine generating multi-view images of a cat from a camera with a circular motion revolving about the cat). This is the case for the existing methods like SPAD and CAT3D as you may have already seen.
> 
> Let us know if you have further questions.

Thank you very much, it makes sense. Again, thanks for your reply!
